README.md

Cleaned and updated README.md

---

src/captcha.py
tests/captcha_tests.py

As mentioned in #133 
Added focus on the captcha window, and focus on the input box, too.🥂🥂

Forced focus on captcha window

---

src/utils.py

Updated "filter_centers_by_age" for centers with both age grp slots.

Updated "filter_centers_by_age" for centers with both age grp slots

---

src/covid-vaccine-slot-booking.py
src/utils.py

Add support for available capacity by dose number

---

src/utils.py

Add option for Sputnik V

---

src/utils.py

Updated date format to dd-mm-yyyy to search a slot for specific date as mentioned in #204 
Please review

Updated date format for searching from a specific date

---

src/covid-vaccine-slot-booking.py
src/utils.py

Temporary workaround until support for rescheduling is added. Please revert once we have support. (#165)
Sample output
```
The following appointments are active! Please cancel them manually first to continue
+-------+------------------+------------------------+--------------+--------+------------+-----------------+
|   idx | beneficiary      | name                   | state_name   |   dose | date       | slot            |
+=======+==================+========================+==============+========+============+=================+
|     1 | John Doe         | P.M.C.H.               | Bihar        |      1 | 20-05-2021 | 09:00AM-11:00AM |
+-------+------------------+------------------------+--------------+--------+------------+-----------------+
|     2 | Jean Doe         | P.M.C.H. …
```

Ask to cancel before rescheduling center

---

src/utils.py

Fix for issue  https://github.com/bombardier-gif/covid-vaccine-booking/issues/222

read fee_type from center instead of session

---

src/utils.py

When no viable options, set slots_available = False

Bugfix when no viable options

---

tests/captcha_tests.py

Removed old anti-captcha tests and replaced with test for @shailesh 's implementation of auto-captcha
Console Output:
```
Installed tkinter_version: 8.6.8 
----------------------------------------------------------------------------------------------------
Opening test window. Click on "Quit" to run further tests
window opening ...
Yeah !!! you have entered captcha. This means you are all set to render required captcha at the time of booking ...
Started solving captcha...
Captcha solve success: SNNvu
It took 0.00067 seconds to solve captcha
```

Modified captcha tests for latest auto captcha

---

src/covid-vaccine-slot-booking.py

Re-initialize token variable after it is found invalid

Bugfix OTP re-validate

---

src/covid-vaccine-slot-booking.py
src/utils.py

-  General use when you are in tier-III or town or village where single PIN code is sufficient
- N PIN codes will be counted as N different API calls
- **Granular but more API calls**
-  General use when you are OK to take vaccine in anywhere in district. Usually tier-I cities.
- N districts will be counted as N different API calls
- **Broader but less API calls**
-  General use when you are OK to take vaccine in anywhere in district. Usually tier-I cities.
- Search#2 filter by specified PIN codes 
- N districts will be counted as N different API calls
- **Granular but less API calls too**

Added 3rd type of slot search option which is optimized for API calls.

---

src/utils.py

Bug fix for start date

---

.github/release-drafter.yml
.github/workflows/main.yml
.github/workflows/release-drafter.yml
src/covid-vaccine-slot-booking.py
src/utils.py

this pr fixes #308, #304, #300

Fixes #308, #304, #300

---

src/utils.py

Fixes #300 
Added line to copy changes to pin_code_location_dtls
For People who have already run the script once, either start the process again or modify your existing json file
replace => pin_code_location_dtls: []
with => pin_code_location_dtls: [copy the location_dtls key value here]

[300] Fixes location search issue for option 1

---

src/covid-vaccine-slot-booking.py
src/ratelimit.py
src/utils.py

Fixes #381 and #382 
Wait for 5 seconds and warn the user so that he can fix himself instead of raising an issue on github

Handle rate limiting. fixes #381 and #382

---

src/covid-vaccine-slot-booking.py
src/utils.py

1. Ability to pass mobile from cli.
2. Ability to specify config
3. New flag called no-tty to avoid inputs
4. Allow to configure KVDB Bucket Id.
5. Allow to turn off beeps.
6. Bug fix otp_pref is accessed before assignment (comes in case token is passed from cli)
7. Immediate refresh on Ctrl + C

cli options mobile, config and no-tty added, configurable kvdb and beeps, bug fix of otp_pref, immediate refresh

---

Dockerfile
README.md
docker.sh

Added a docker file. Makes it easier to run this script if you don't want to install python on your system (or you have older version).

Add Dockerfile

---

src/covid-vaccine-slot-booking.py
src/utils.py

KVDB buckets are not required in case the user opts for manual OTP flow.

Avoiding the mandatory input of KVDB bucket in case of manual OTP

---

src/utils.py

`&vaccine={vaccine_type}` query param doesn't work anymore.
We will need to filter by vaccine, after the API call has been made to fetch all vaccines.

filtering by vaccine type #451

---

src/utils.py

Reverts bombardier-gif/covid-vaccine-booking#453
vaccine filter is working fine as per my observation. Hence, requesting to revert the PR.

Revert "filtering by vaccine type #451"

---

.gitignore
README.md
windows.bat

This makes it easier to run in windows machine.
This PR will stay as Draft as long as I can test it out myself

Added portable python from @vishalv26/covid-vaccine-booking

---

.github/workflows/main.yml

Corrected a minor bug for not pushing correctly to docker packages.

GitHub Action Docker bug fix

---

src/utils.py

Modified dose no function | bug fix for #277#239

---

docs/AWS.md
docs/aws.template

Provided a CF template to run on AWS with instruction on how to import template.

Making it easy to run on AWS

---

src/utils.py

For find by date, added feature to search for today and tomorrow.
I have tested once. 
plz test and share if it works fine in comments

Added feature to search for today and tomorrow

---

src/covid-vaccine-slot-booking.py

Small PR to add a cli argument for accepting kvdb.io bucket 
Edit:
Makes it easy to use --no-tty option on local; I wanted to avoid environment variables on local.
Have not tried on AWS but doesn't seem like it would affect anything as it would takes the env variable if arg is absent.

Add --kvdb-bucket argument

---

README.md
src/captcha.py
src/covid-vaccine-slot-booking.py
src/ratelimit.py
src/utils.py

- I've added the Functionality of Downloading Appointment Slip as mentioned in #385 .
- Originally Added in #472 but the code had to be changed.
- Re-structued Python code for better visibility and understanding.

Appointment Slip Download + Code Re-structured

---

requirements.txt

issue #529
for error : modulenotfounderror: No module named 'playsound'

update in requirement.txt

---

README.md

it should be 
sudo modprobe pcspkr
instead modeprobe

small typo in readme #536

---

src/utils.py

As mentioned by @bombardier-gif in #538 .

Temporary Solution for "18 and above" bug
